%\VignetteIndexEntry{OrgMassSpecR Examples}

\documentclass[11]{article}
\usepackage{Sweave}
\pagestyle{plain}
%\addtolength{\hoffset}{-1cm}
%\addtolength{\textwidth}{2cm}
\setlength{\parindent}{0pt}
\setlength{\parskip}{1ex plus 0.5ex minus 0.2ex}

\SweaveOpts{keep.source=TRUE}

\begin{document}
\title{Vignette for \texttt{OrgMassSpecR}: Examples}
\author{Nathan G. Dodder}
\date{September 2010}
\maketitle

\section{Introduction}   

\texttt{OrgMassSpecR} is a package for organic/biological mass spectrometry.  This vignette demonstrates some of the functions in a larger context than the help file examples.

First, load the package.

<<>>=
library(OrgMassSpecR)
@

\section{Small Molecules}

The functions \texttt{MonoisotopicMass} and \texttt{IsotopicDistribution} assist in identifying unknown mass spectra, or in confirming peak identities in known spectra.  The monoisotopic mass of DDE, a breakdown product of the pesticide DDT, is calculated as follows.

<<>>=
MonoisotopicMass(formula = list(C=14, H=8, Cl=4))
@

The monoisotopic masses due to successive losses of chlorine, which are observed in the electron impact mass spectrum of DDE, are calculated by repeated calls to \texttt{MonoisotopicMass}.

<<>>=
MonoisotopicMass(formula = list(C=14, H=8, Cl=3))
MonoisotopicMass(formula = list(C=14, H=8, Cl=2))
# etc, ...
@

The monoisotopic mass of $^{13}$C$_{12}$ labeled DDE (an internal/surrogate standard for the quantification of DDE) is calculated using the list component \texttt{x}. 

<<>>=
MonoisotopicMass(formula = list(C=2, H=8, Cl=4, x = 12), 
                 isotopes = list(x = 13.0033548378))
@

The isotopic distribution of DDE is simulated using \texttt{IsotopicDistribution}.  This function uses a binning approach based on \texttt{sample}, where the probabilities are the natural abundances of the isotopes.  The output of this function is a table, but it is often helpful to plot the distribution.

<<>>=
dde.dist <- IsotopicDistribution(formula = list(C=14, H=8, Cl=4))
dde.dist
@

\begin{center}
<<fig=TRUE>>=
# plot
library(lattice)
print(xyplot(percent ~ mz,
  data = dde.dist,
  type = "h",
  xlab = "m/z",
  ylab = "intensity (%)",
  main = "Isotopic Distribution, DDE")
)
@
\end{center}

The similarity between two mass spectra can be examined using \texttt{SpectrumSimilarity}.  This function makes a head-to-tail plot of the spectra and calculates a mass spectral similarity score based on the dot product of the two mass-aligned intensity vectors.  See the help file for an example.

\section{Proteins and Peptides}

The following functions assist in setting up multiple reaction monitoring (MRM) assays for the quantification of proteins.  These assays require the selection of ``signature peptides" \cite{1,2}.

Peptides resulting from a protein digestion with trypsin or pepsin can be prediced using \texttt{Digest}.

<<>>=
hsa <- Digest(example.sequence)
head(hsa)
@

Next, peptides between 5 and 12 amino acids are selected (the range is somewhat arbitrary; small peptides may not be specific to the target protein, large peptides may have low sensitivity).

<<>>=
hsa.sub <- subset(hsa, nchar(hsa$peptide) >= 5 & nchar(hsa$peptide) <= 12)
head(hsa.sub)
@

The filtered table can be used to screen a digest for the presence of these peptides by operating the triple quadrupole instrument in Q1 selected ion mode with Q2 and Q3 open.  Assuming peptides \texttt{YLYEIAR} and \texttt{AEFAEVSK} are found (the number is kept small for this example), the next step is to determine their most intense MRM transitions.  The b- and y-ions of the peptides are calculated using \texttt{FragmentPeptide}.

<<>>=
transitions <- FragmentPeptide(c("YLYEIAR", "AEFAEVSK"))
head(transitions)
@

This table can be used to screen the MRM transitions.  The table is formatted to facilitate easy selection of the appropriate precursor ion and product ion charge states.

\emph{Note}: both \texttt{Digest} and \texttt{FragmentPepetide} by default use \texttt{IAA=TRUE}.  This argument specifies iodoacetylated cysteine.  

Once the signature peptides for the target protein have been determined, MRM transitions for the internal standard peptides must be set up.  Generally, either synthetic $^{13}$C-labeled peptides or $^{15}$N-labeled proteins are used.  $^{15}$N-labeled proteins are added prior to the digestion to yield $^{15}$N-labeled peptides. 

The MRM transitions for \texttt{YLYEIAR} with the terminal arginine $^{13}$C-labeled are calculated as follows.

<<>>=
c13.labeled <- FragmentPeptide("YLYEIAr", custom = list(code = "r", 
  mass = MonoisotopicMass(formula = list(C=6, H=12, N=4, O=1), 
                          isotopes = list(C=13.0033548378))))
head(c13.labeled)
@

The MRM transitions for fully $^{15}$N-labeled \texttt{YLYEIAR} are calculated as follows.  Note that \texttt{FragmentPeptide}, and \texttt{Digest}, do not label the nitrogens incorporated into the peptide due to iodoacetamide treatment (when \texttt{IAA = TRUE} and \texttt{15N = TRUE}). 

<<>>=
n15.labeled <- FragmentPeptide("YLYEIAR", N15 = TRUE)
head(n15.labeled)
@

An acquired full-scan peptide spectrum can be plotted using \texttt{PeptideSpectrum}.  The peptide sequence must be known to determine the fragment ion identities (i.e., the function does not sequence the peptide \textit{de novo}).  This function was created to catalog full-scan mass spectra and double check that the most intense ions observed by MRM screens correspond to the most intense ions observed in full scan mode.  See the help file for an example.   

Before use as an internal standard, the $^{15}$N incorporation in the expressed protein should be measured.  The incorporation should be high enough that the isotopic envelop of the internal standard signature peptide does not overlap with that of the corresponding unlabeled signature peptide.

The isotopic distribution of $^{15}$N labeled peptides is calculated using \texttt{IsotopicDistributionN}.

\begin{center}
<<fig=TRUE>>=
theoretical.dist <- IsotopicDistributionN("YEVQGEVFTKPQLWP", incorp = 0.99)
print(xyplot(percent ~ mz,
  data = theoretical.dist,
  type = "h",
  xlab = "m/z",
  ylab = "intensity (%)",
  main = "Theoretical Isotopic Distribution, YEVQGEVFTKPQLWP, 99% 15N")
)
@
\end{center}

The theoretical distribution is compared to the measured distribution.  In this example, visual inspection shows the incorporation in the peptide, and by extension the protein, is about 99\% (although in a real experiment more than one peptide should be measured to confirm the results).  See the IsotopicDistributionN help file for an example calculating and plotting a range of $^{15}$N incorporations. 

\begin{center}
<<fig=TRUE>>=
example.spectrum.labeled$percent <- with(example.spectrum.labeled, 
  intensity / max(intensity) * 100)
print(xyplot(percent ~ mz,
  data = example.spectrum.labeled,
  type = "l",
  xlab = "m/z",
  ylab = "intensity (%)",
  main = "Measured Isotopic Distribution, YEVQGEVFTKPQLWP")
)
@
\end{center}

\begin{thebibliography}{9}
\bibitem{1}
Addona TA, Abbatiello SE, Schilling B, Skates SJ, Mani DR, Bunk DM, Spiegelman CH, Zimmerman LJ, Ham AJ, Keshishian H, Hall SC, Allen S, Blackman RK, Borchers CH, Buck C, Cardasis HL, Cusack MP, Dodder NG, Gibson BW, Held JM, Hiltke T, Jackson A, Johansen EB, Kinsinger CR, Li J, Mesri M, Neubert TA, Niles RK, Pulsipher TC, Ransohoff D, Rodriguez H, Rudnick PA, Smith D, Tabb DL, Tegeler TJ, Variyath AM, Vega-Montoto LJ, Wahlander A, Waldemarson S, Wang M, Whiteaker JR, Zhao L, Anderson NL, Fisher SJ, Liebler DC, Paulovich AG, Regnier FE, Tempst P, Carr SA. Multi-site assessment of the precision and reproducibility of multiple reaction monitoring-based measurements of proteins in plasma. \textit{Nature Biotechnology}, \textbf{2009}, 27, 633-641.
\bibitem{2}
Liao WL, Heo GY, Dodder NG, Pikuleva IA, Turko IV.  Optimizing the conditions of a multiple reaction monitoring assay for membrane proteins: quantification of cytochrome P450 11A1 and adrenodoxin reductase in bovine adrenal cortex and retina. \textit{Analytical Chemistry}, \textbf{2010}, 82, 5760-5767. This reference used OrgMassSpecR as described here. 
\end{thebibliography}

\end{document}
